Sys.setlocale("LC_ALL", locale="pt_PT.UTF-8")
rm(list=ls())
load(file="var.Rdata")
library(neuralnet)
library(e1071) 
library(dplyr)
library(party)
library(tm)
library(caret)
library(rpart)
library(rpart.plot)
library(e1071)
library(nnet)
library(wordcloud)
library(Rserve)
#install.packages('neuralnet')
